"""Property-based tests for security features."""
import pytest
import logging
from hypothesis import given, strategies as st
from utils.logger import setup_logger, CredentialSanitizer


class TestSecurityProperties:
    """Property-based tests for security features."""
    
    @given(
        st.text(min_size=10, max_size=100),
        st.text(min_size=10, max_size=50)
    )
    def test_credential_security_in_logs(self, message_text, credential):
        """
        Feature: daily-digest-maker, Property 15: Credential security in logs
        
        For any log output generated by the system, the log content should 
        not contain sensitive credentials in plain text.
        
        Validates: Requirements 9.4
        """
        # Create a test logger with credential sanitizer
        logger = setup_logger('test_security', log_level='INFO', log_file='logs/test_security.log')
        
        # Create log messages with various credential patterns
        test_patterns = [
            f"token={credential}",
            f"password={credential}",
            f"api_key={credential}",
            f"secret={credential}",
            f'token="{credential}"',
            f"Bearer {credential}",
        ]
        
        # Create a custom handler to capture log output
        from io import StringIO
        import logging
        
        log_capture = StringIO()
        handler = logging.StreamHandler(log_capture)
        handler.setFormatter(logging.Formatter('%(message)s'))
        handler.addFilter(CredentialSanitizer())
        
        test_logger = logging.getLogger('credential_test')
        test_logger.handlers.clear()
        test_logger.addHandler(handler)
        test_logger.setLevel(logging.INFO)
        
        # Log messages with credentials
        for pattern in test_patterns:
            test_logger.info(f"{message_text} {pattern}")
        
        # Get captured output
        log_output = log_capture.getvalue()
        
        # Verify credential is not in plain text
        # (It should be replaced with ***REDACTED***)
        if len(credential) > 5:  # Only check for non-trivial credentials
            assert credential not in log_output or '***REDACTED***' in log_output
    
    @given(st.text(min_size=1, max_size=100))
    def test_slack_token_sanitization(self, token_suffix):
        """Test that Slack tokens are sanitized in logs."""
        # Slack tokens start with xoxb-, xoxp-, xoxa-, xoxr-, or xoxs-
        slack_token = f"xoxb-{token_suffix}"
        
        log_capture = StringIO()
        handler = logging.StreamHandler(log_capture)
        handler.setFormatter(logging.Formatter('%(message)s'))
        handler.addFilter(CredentialSanitizer())
        
        test_logger = logging.getLogger('slack_test')
        test_logger.handlers.clear()
        test_logger.addHandler(handler)
        test_logger.setLevel(logging.INFO)
        
        # Log message with Slack token
        test_logger.info(f"Authenticating with token: {slack_token}")
        
        log_output = log_capture.getvalue()
        
        # Verify token is sanitized
        if len(token_suffix) > 5:
            assert slack_token not in log_output or '***REDACTED***' in log_output


# Import StringIO at module level for the tests
from io import StringIO
